name: Nightly MM Build

on:
    schedule:
      - cron: '30 1 * * *'
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        wget https://github.com/MoonModules/WLED/archive/refs/heads/mdev.zip -O /tmp/mm.zip
        unzip /tmp/mm.zip -d /tmp

    - name: Run PlatformIO
      run: pio run -c /tmp/WLED-mdev/platformio.ini-e esp32_4MB_max
      env:
        PLATFORMIO_CI_SRC: /tmp/WLED-mdev
